# Generated by Django 3.2.5 on 2021-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News', models.TextField(verbose_name='Новость')),
                ('Author', models.CharField(max_length=50, verbose_name='Автор')),
            ],
        ),
    ]
