# Generated by Django 3.2.5 on 2021-07-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='News',
        ),
        migrations.AddField(
            model_name='news',
            name='SomeNews',
            field=models.TextField(default='новость', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='news',
            name='TitleNews',
            field=models.CharField(default='название', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Author',
            field=models.CharField(default='автор', max_length=50, verbose_name='Автор'),
        ),
    ]
