# Generated by Django 3.2.5 on 2021-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210727_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='TimeCreate',
            field=models.DateTimeField(default='2000-01-01 06:00', verbose_name='Время создания'),
        ),
    ]
