# Generated by Django 3.2.5 on 2021-07-27 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_timecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='TimeCreate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 13, 15, 26, 206755), verbose_name='Время создания'),
        ),
    ]
