# Generated by Django 3.2.5 on 2021-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_news_timecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='SomeNews',
            field=models.TextField(verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='TimeCreate',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='TitleNews',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
