# Generated by Django 3.2.5 on 2021-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210727_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='TimeCreate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
