# Generated by Django 3.2.5 on 2021-07-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_news_timecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Image',
            field=models.ImageField(default='notfing.jpg', upload_to='images/'),
        ),
    ]
