# Generated by Django 3.2.5 on 2021-07-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(default='images/notfing.jpg', upload_to='images/'),
        ),
    ]
