# Generated by Django 3.2.5 on 2021-07-28 08:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20210728_1340'),
        ('main', '0009_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
